version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
    restart: on-failure
    ports:
      - "443:443" 
    volumes:
        - Wordpress:/var/www/wordpress
      # - /home/agouet42/data/wordpress:/var/www/wordpress
      
       #attention pas d espaces, bind mount
    depends_on:
      - wordpress
    networks:
     - inception
    env_file: .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb 
    volumes:
      - Vmariadb:/var/lib/mysql
      # - /home/agouet42/data/mariadb:/var/lib/mysql
       #attention pas d espaces, bind mount
    restart: unless-stopped
    expose:
      - "3306"
    networks:
     - inception
    env_file: .env
    healthcheck:
      test: [ "CMD", "mysql", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 30s
      timeout: 5s
      retries: 3

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      mariadb:
        condition: service_healthy #sans mariadb wordpress ne peut pas marcher
    env_file: .env
    volumes:
      - Wordpress:/var/www/wordpress
      # - /home/agouet42/data/wordpress:/var/www/wordpress #attention pas d espaces, bind mount
    networks:
      - inception
    restart: on-failure
    expose:
      - "9000"


networks:
  inception:
    driver: bridge


volumes:
  Wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/agouet42/data/wordpress
  Vmariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/agouet42/data/mariadb
    