version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
    restart: on-failure
    ports:
      - "443:443" 
    volumes:
      - type: bind
        source:  /home/agouet42/data/wordpress
        target: /var/www/wordpress
    depends_on:
      - wordpress
    networks:
     - inception
    env_file: .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb 
    # volumes:
    #   - type: bind
    #     source:  /home/agouet42/data/mariadb
    #     target: /var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
     - inception
    env_file: .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    depends_on:
      - mariadb
    env_file: .env
    volumes:
      - /home/agouet42/data/wordpress:/var/www/wordpress
    #   - type: bind
    #     source:  /home/agouet42/data/wordpress
    #     target: /var/www/wordpress
    networks:
      - inception
    restart: on-failure
    expose:
      - "9000"


networks:
  inception:
    driver: bridge
