version: '3'

services:
  nginx:
    container_name: nginx
    build: 
      context: requirements/nginx
    restart: on-failure
    ports:
      - "443:443"
  
    # volumes: 
      # - wordpress: /var/www/html  
      # - wordpress: /var/www/wordpress
    # depends_on:
      # - wordpress
    networks:
     - inception
    #env_file: .env

  mariadb:
    container_name: mariadb
    build: requirements/mariadb 
    # volumes:
    #   - type: 'bind'
    #     # source:  /home/agouet/data 
    #     source: requirements/mariadb/tools
    #     target: /var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    networks:
     - inception
    #env_file: .env


networks:
  inception:
    driver: bridge